### ISSUE TITLE
[Database] Standardize DatabaseGisInterfaceImplementation Unit Tests Name

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/csi-3370-software-project#142]
**Describe the bug**
Currently, the `DisplayName` of the `DatabaseGisInterfaceImplementationTests` reads `Database GisInterface Test` which doesn't match the other names and makes it more difficult to search the logs.

**Expected behavior**
For clarity of reading the unit test logs, can you please update the `DisplayName` of the `DatabaseGisInterfaceImplementationTests` class to `DatabaseGisInterfaceImplementation Unit Tests`? Thank you!

**Comment by MathewYaldo** [comment]
I have created the pull request (#144). Please let me know if that is good. Will let the team know to look for more instances of these
