### ISSUE TITLE
[Display_01] Change Method Passing Variable

### ISSUE THREAD

**Issue by reedsikorskiOU** [andrewdimmer/csi-3370-software-project#74]
**Describe the bug**
Change methods in displayinterfaceimplementation to passing satellite objects rather than satellite names so it is easier to test,

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. [You can upload them via the edit menu.]

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10 Home (1903)]
- JDK Version [e.g. 11.0.8]

**Additional context**

**Comment by andrewdimmer** [comment]
While we're making the update, I would update the return type as well. In the mean time, I've tagged `Admin` and added the `BREAKING CHANGE` label so we know that this does change the public API. @reedsikorskiOU Can you do the updates for `DisplayGpsInterface`, `DisplayGpsReceiver` and  `DisplayGpsManager` (both the UML and .java file), the 3 production classes that implement them (UML), and the 3 stubs (UML) that implement them?

**Comment by EC01EC** [comment]
Fixed with finishing of merging of PRs #73 #92 and #93
