### ISSUE TITLE
[Middleware_01] Changed MiddlewareGisInterface Method Names

### ISSUE THREAD

**Issue by jvalentini555** [andrewdimmer/csi-3370-software-project#98]
**Describe the bug**
Middleware 1 changed public interface method names for MiddlewareGisInterface.

**Expected behavior**
Changed for the separate use cases.

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10 Home (1903)]
- JDK Version [e.g. 11.0.8]

**Additional context**

**Comment by andrewdimmer** [comment]
All production classes that use this are code complete, so the issue should be resolved an no longer needs to be tracked.
